# Generated by Django 4.2.6 on 2023-11-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=100, verbose_name='название курса')),
                ('kurs_avatar', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='картинка')),
                ('kurs_description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100, verbose_name='название урока')),
                ('lesson_avatar', models.ImageField(blank=True, null=True, upload_to='school/', verbose_name='картинка урока')),
                ('lesson_description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapay', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('payment', models.FloatField(blank=True, null=True, verbose_name='сумма оплаты')),
                ('paymentmethod', models.CharField(choices=[('transfer', 'перевод на счет'), ('cash', 'наличными')], max_length=35, verbose_name='способ оплаты')),
                ('kurspay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurspay', to='school.kurs', verbose_name='оплата курса')),
                ('lessonpay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessonpay', to='school.lesson', verbose_name='оплата урока')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
